/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__reduction__quant__native___native
#define __PYX_HAVE__reduction__quant__native___native


/* "reduction/quant/native/_native.pyx":85
 *     return output_vals[ :, :output_index ]
 * 
 * cdef public enum BoundsType:             # <<<<<<<<<<<<<<
 *     sigma = 0
 *     percentile = 1
 */
enum BoundsType {
  sigma = 0,
  percentile = 1
};

#ifndef __PYX_HAVE_API__reduction__quant__native___native

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__reduction__quant__native___native */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_native(void);
#else
PyMODINIT_FUNC PyInit__native(void);
#endif

#endif /* !__PYX_HAVE__reduction__quant__native___native */
